---
# tasks file for firewall_iptables
- name: install iptables-persistent 
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
  become: true

- name: Allow only control_node
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    source: 0.0.0.0
    jump: ACCEPT
  become: true

- name: Allow only control_node 
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: 22
    source: 0.0.0.0
    jump: ACCEPT
  become: true

- name: Allow only proxy on HTTP
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    source: 172.20.10.14
    jump: ACCEPT
  become: true

- name: Allow only proxy on HTTP
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: 80
    source: 172.20.10.14
    jump: ACCEPT
  become: true

- name: Allow only proxy on HTTPS
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    source: 172.20.10.14
    jump: ACCEPT
  become: true

- name: Allow only proxy on HTTPS
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: 443
    source: 172.20.10.14
    jump: ACCEPT
  become: true

- name: icmp accept
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
    comment: Allow ping
  become: true

- name: icmp accept
  ansible.builtin.iptables:
    chain: OUTPUT
    protocol: icmp
    jump: ACCEPT
    comment: Allow ping
  become: true

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: true

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: OUTPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: true

# - name: Set the policy for the INPUT chain to DROP
#   ansible.builtin.iptables:
#     chain: INPUT
#     policy: DROP
#   become: true

# - name: Set the policy for the OUTPUT chain to ACCEPT
#   ansible.builtin.iptables:
#     chain: OUTPUT
#     policy: ACCEPT
#   become: true

# - name: Set the policy for the FORWARD chain to DROP
#   ansible.builtin.iptables:
#     chain: FORWARD
#     policy: DROP
#   become: true

- name: persistent rules
  ansible.builtin.shell: iptables-save > /etc/iptables/rules_v4
  become: true